import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
    backgroundColor: "#0a0f1c",
  },
  topSection: {
    flex: 2,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#facc15",
    textAlign: "center",
  },
  subtitle: {
    color: "#cbd5e1",
    fontSize: 14,
    textAlign: "center",
  },
  iconCircle: {
    marginTop: 8,
    backgroundColor: "rgba(30,41,59,0.9)",
    padding: 20,
    borderRadius: 80,
    shadowColor: "#000",
    shadowOpacity: 0.8,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    ...Platform.select({ android: { elevation: 6 } }),
  },
  statRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  statPill: {
    backgroundColor: "rgba(2,6,23,0.6)",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignItems: "center",
  },
  statVal: { color: "#e5e7eb", fontWeight: "800", fontSize: 14 },
  statLabel: { color: "#94a3b8", fontSize: 10 },
  stopBtn: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "#ef4444",
  },
  stopText: { color: "#fff", fontWeight: "800", fontSize: 13 },
  bottomSection: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 8,
    gap: 8,
  },
  resultCard: {
    backgroundColor: "rgba(17, 24, 39, 0.9)",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
  },
  resultTitle: {
    color: "#e5e7eb",
    fontWeight: "800",
    fontSize: 14,
    marginBottom: 4,
  },
  filePath: {
    color: "#94a3b8",
    fontSize: 10,
  },
  resultActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  primaryBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#38bdf8",
    alignItems: "center",
  },
  primaryText: { color: "#0b1220", fontWeight: "800", fontSize: 13 },
  secondaryBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(2,6,23,0.65)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.35)",
    alignItems: "center",
  },
  secondaryText: { color: "#e2e8f0", fontWeight: "700", fontSize: 13 },
  backButton: {
  position: "absolute",
  top: 16,
  left: 16,
  zIndex: 10,
  padding: 8,
},
});